### ISSUE TITLE
Cloudflare pages deployment?

### ISSUE THREAD

**Issue by aiiven** [passlock-dev/passlock#22]
Hello.

I tested the stack with preline / sveltekit but I have an issue to deploy it on Cloudflare Pages related to Prisma.
I am not familiar with Prisma so it might be something obvious I missed?

`<html>
<body>

18:56:51.276 | Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
-- | --

18:56:51.276 | at new PrismaClient (/opt/buildhome/repo/node_modules/.pnpm/@prisma+client@5.19.1_prisma@5.19.1/node_modules/.prisma/client/default.js:43:11)

18:56:51.276 | at file:///opt/buildhome/repo/.svelte-kit/output/server/chunks/db.js:3:16

18:56:51.276 | at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

18:56:51.276 | Emitted 'error' event on Worker instance at:

18:56:51.276 | at [kOnErrorMessage] (node:internal/worker:300:10)

18:56:51.277 | at [kOnMessage] (node:internal/worker:311:37)

18:56:51.277 | at MessagePort.<anonymous> (node:internal/worker:212:57)

18:56:51.277 | at [nodejs.internal.kHybridDispatch] (node:internal/event_target:741:20)

18:56:51.277 | at exports.emitMessage (node:internal/per_context/messageport:23:28)

18:56:51.277 |  

18:56:51.277 | Node.js v18.17.1

18:56:51.326 | Failed: Error while executing user command. Exited with error code: 1

18:56:51.335 | Failed: build command exited with code: 1

18:56:52.452 | Failed: error occurred while running build command

</body>
</html>`

**Comment by thobson** [comment]
Are you using the default SQLite database? If so this won't work on Cloudflare (in fact I wouldn't use SQLite in any production environment). You'd be better off using something like [D1](https://developers.cloudflare.com/d1/), Prisma has experimental [D1 support](https://www.prisma.io/docs/orm/overview/databases/cloudflare-d1)

**Comment by aiiven** [comment]
Yes it was a bit of a naive deployment.

Would you mind showing how we could replace SQLite by Postgres or Supabase?

**Comment by thobson** [comment]
No further updates so I’m assuming this worked out. Happy to reopen if needed
